# Generated by Django 3.1.13 on 2022-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedata',
            name='ok',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
