# Generated by Django 3.1.13 on 2022-04-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_certificatedata_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatedata',
            name='ok',
        ),
    ]
