# Generated by Django 3.1.13 on 2022-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_certificatedata_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='CansysData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256)),
                ('protocols_ports', models.CharField(max_length=256)),
                ('longitude', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('timezone', models.CharField(max_length=256)),
                ('continent', models.CharField(max_length=256)),
                ('registered_country', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('asn', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=2000)),
                ('dns_names', models.TextField(blank=True, null=True)),
                ('os', models.TextField(blank=True, null=True)),
                ('last_updated_at', models.CharField(max_length=256)),
            ],
        ),
    ]
