# Generated by Django 3.1.13 on 2022-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220415_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMonitoringData',
            fields=[
                ('domain_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=256)),
                ('ip_second', models.CharField(blank=True, max_length=256, null=True)),
                ('MX_records', models.TextField()),
                ('mail_A_record_ip', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
