# Generated by Django 3.1.13 on 2022-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_websitemonitoringdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemonitoringdata',
            name='expiry',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='websitemonitoringdata',
            name='monitored',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitemonitoringdata',
            name='web_status',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
