# Generated by Django 3.1.13 on 2022-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_twisteddnsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('search_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('profile_image_url', models.TextField()),
                ('full_text', models.TextField()),
                ('retweet_count', models.CharField(max_length=255)),
                ('verified', models.CharField(max_length=255)),
                ('entities', models.JSONField()),
            ],
        ),
    ]
